spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  r2dbc:
    url: r2dbc:h2:mem:///meli?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: 'sa'
    password: ''
  redis:
    url: redis://localhost:6379
  data:
    redis:
      repositories:
        enabled: false
